### ISSUE TITLE
Each returns the original object not mutated object

### ISSUE THREAD

**Issue by stagfoo** [ExOLever/exo-element-kit#2]
Hey all,
https://github.com/ExOLever/exo-element-kit/blob/1d37143d46b8b08958ed5aec3397a6d0285c8f7f/src/main.ts#L21-L25
the each function return the original object not the mutated one. ([docs](https://lodash.com/docs#forEach))
Shouldn't it be this?
```js
let obj = {};
// each returns exoElementConfig.attributes
each(exoElementConfig.attributes, function(attr) {
   obj[attr.name] = attr.value;
})
// send the mutated obj to reducer
updateCustomElementAttributes(obj);
```

**Comment by adammunoz** [comment]
right.
